cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name="cart"),
    path("cart-add/", views.cart_add, name="cart_add"),
    path("cart-delete/", views.cart_delete, name="cart_delete"),
    path("cart-update/", views.cart_update, name="cart_update")
]

payment/urls.py
from django.urls import path
from . import views

app_name = "payment"

urlpatterns = [
    path("checkout/", views.checkout, name="checkout"),
    path("order-placed/", views.order_placed, name="order_placed"),
    path("webhook/", views.stripe_webhook)
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.all_products, name="all_products"),
    path('shop/', views.shop, name="shop"),
    path('product/<slug:slug>/', views.product_detail, name="product_detail"),
    path('search/<slug:slug>/', views.get_by_category, name="category")
]

quipy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls")),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('payment/', include("payment.urls")),
    path('orders/', include("orders.urls"))
]

handler404 = "quipy.views.page_not_found"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse

from .cart import Cart
from products.models import Product

# Create your views here.


def cart(request):
    return render(request, 'cart/cart.html')


def cart_add(request):
    cart = Cart(request)

    if request.method == "POST":
        try:
            product_id = int(request.POST.get("productId"))
            product_qty = int(request.POST.get("productQty"))
        except:
            return JsonResponse({"error": "Something went wrong"}, status=500)
        product = get_object_or_404(Product, id=product_id)
        added = cart.add(product=product, qty=product_qty)

        if added == False:
            return JsonResponse({"error": "Item is already in cart"}, status=400)

        cart_qty = cart.__len__()
        return JsonResponse({"qty": cart_qty})


def cart_update(request):
    cart = Cart(request)
    if request.method == "POST":
        try:
            product_id = int(request.POST.get("productId"))
            product_qty = int(request.POST.get("productQty"))
        except:
            return JsonResponse({"error": "Something went wrong"}, status=500)
        cart.update(product=product_id, qty=product_qty)

        cart_qty = cart.__len__()
        cart_subtotal = cart.get_subtotal_price()
        return JsonResponse({"qty": cart_qty, "subtotal": cart_subtotal})


def cart_delete(request):
    cart = Cart(request)

    if request.method == "POST":
        try:
            product_id = int(request.POST.get("productId"))
        except:
            return JsonResponse({"error": "Something went wrong"}, status=500)
        cart.delete(product_id=product_id)

        cart_qty = cart.__len__()
        cart_subtotal = cart.get_subtotal_price()
        return JsonResponse({"qty": cart_qty, "subtotal": cart_subtotal})

templates/cart/cart.html
{% extends 'base.html' %} 
{% load static %} 

{% block meta %}
<title>Cart | Quipy</title>
<link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet" />
<link href="{% static 'css/price-range.css' %}" rel="stylesheet" />
<link href="{% static 'css/animate.css' %}" rel="stylesheet" />
{% endblock %} 

{% block content %} 

{% include 'navbar.html' %}
<section id="cart_items">
	<div class="container">
		<div class="breadcrumbs">
			<ol class="breadcrumb">
				<li><a href="{% url 'products:all_products' %}">Home</a></li>
				<li class="active">Shopping Cart</li>
			</ol>
		</div>

		<div class="table-responsive cart_info">
			<table class="table table-condensed">
				<thead>
					<tr class="cart_menu">
						<td class="image">Item</td>
						<td class="description"></td>
						<td class="price">Price</td>
						<td class="quantity">Quantity</td>
						<td class="total">Total</td>
						<td></td>
					</tr>
				</thead>
				<tbody>
					{% for item in cart %} 
					{% with product=item.product %}
					<tr id="row-{{product.id}}">
						<td class="cart_product">
							<a href="{{product.get_absolute_url}}"><img class="cart-product-img"
									src="{{product.get_featured_image.image.url}}"
									alt="{{product.get_featured_image.alt_text}}" /></a>
						</td>
						<td class="cart_description">
							<h4>
								<a href="{{product.get_absolute_url}}">{{product.title}}</a>
							</h4>
						</td>
						<td class="cart_price">
							<p id="price-{{product.id}}" data-price="{{product.regular_price}}">${{product.regular_price}}</p>
						</td>
						<td class="cart_quantity">
							<div class="cart_quantity_button">
								<input class="cart_quantity_input" type="text" id="qty-{{product.id}}" name="quantity" value="{{item.qty}}"
									autocomplete="off" size="2" />
								<button id="update-cart" value="{{product.id}}" style="margin-left: 10px;" class="btn btn-warning">Update</button>
							</div>
						</td>
						<td class="cart_total">
							<p id="total-{{product.id}}" class="cart_total_price">${{item.total_price}}</p>
						</td>
						<td class="cart_delete">
							<button value="{{product.id}}" id="delete-cart" class="btn btn-danger">
								<i class="fa fa-times"></i>
							</button>
						</td>
					</tr>
					{% endwith %} 
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</section>
<!--/#cart_items-->

<section id="do_action">
	<div class="container">
		<div class="heading">
			<h3>Cart Details</h3>
		</div>
		<div class="row">
			<div class="col-sm-6">
				<div class="total_area">
					<ul>
						<li>
							Cart Sub Total
							<span id="subtotal">${{cart.get_subtotal_price}}</span>
						</li>
						<li>Eco Tax <span>$2</span></li>
						<li>Shipping Cost <span>Free</span></li>
						<li>Total <span>$61</span></li>
					</ul>
					<a class="btn btn-default check_out" href="{% url 'payment:checkout' %}">Check Out</a>
				</div>
			</div>
		</div>
	</div>
</section>
<!--/#do_action-->
{% include 'footer.html' %} 
{% endblock content %} 

{% block scripts %}
<script src="{% static 'js/price-range.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/removeFromCart.js' %}"></script>
<script src="{% static 'js/updateCart.js' %}"></script>
<script>
	const deleteCartBtns = document.querySelectorAll("#delete-cart");
	const cartCount = document.querySelector("#cart-count");
	const subtotalEl = document.querySelector("#subtotal");

	deleteCartBtns.forEach((btn) => {
		btn.addEventListener("click", function (e) {
			e.preventDefault();
			removeFromCart(
				btn,
				cartCount,
				subtotalEl,
				"{{csrf_token}}",
				"{% url 'cart:cart_delete' %}"
			);
		});
	});

	const updateCartBtns = document.querySelectorAll("#update-cart");

	updateCartBtns.forEach((btn) => {
		btn.addEventListener("click", function (e) {
			e.preventDefault();

			const qtyInput = document.querySelector("#qty-" + btn.value);
			const productTotalEl = document.querySelector("#total-"+ btn.value);
			const productPriceEl = document.querySelector("#price-" + btn.value);
			const productPrice = productPriceEl.getAttribute("data-price");
			console.log(productPrice);

			updateCart(
				btn.value,
				qtyInput.value,
				productPrice,
				cartCount,
				productTotalEl,
				subtotalEl,
				"{{csrf_token}}",
				"{% url 'cart:cart_update' %}"
			);
		});
	});

</script>
{% endblock scripts %}