accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views
from .forms import PasswordResetForm, PasswordResetConfirmForm


app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/",
         views.account_activate, name="activate"),
    path('login-user/', views.login_user, name="login-user"),
    path('logout/', views.logout_user, name="logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('edit-account/', views.edit_account, name="edit_account"),
    path("delete-account/", views.delete_account, name="delete_account"),
    path("password_reset/", auth_views.PasswordResetView.as_view(
        template_name="accounts/password_reset_form.html",
        success_url="password_reset_email_confirm/",
        email_template_name="accounts/password_reset_email.html",
        form_class=PasswordResetForm
    ), name="password_reset"),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/accounts/password_reset_complete/",
            form_class=PasswordResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="accounts/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_complete/",
        TemplateView.as_view(template_name="accounts/reset_status.html"),
        name="password_reset_complete",
    ),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name="cart"),
    path("cart-add/", views.cart_add, name="cart_add"),
    path("cart-delete/", views.cart_delete, name="cart_delete"),
    path("cart-update/", views.cart_update, name="cart_update")
]

quipy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls")),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('payment/', include("payment.urls")),
    path('orders/', include("orders.urls"))
]

handler404 = "quipy.views.page_not_found"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.validators import validate_email


class CustomAccountManager(BaseUserManager):
    def create_superuser(self, email, username, first_name, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, username, first_name, password, **other_fields)

    def create_user(self, email, username, first_name, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, username=username,
                          first_name=first_name, **other_fields)
        user.set_password(password)
        user.save()
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    start_date = models.DateTimeField(auto_now_add=True)
    about = models.TextField(_(
        'about'), max_length=500, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name']

    def email_user(self, subject, message):
        send_mail(
            subject,
            message,
            "l@1.com",
            [self.email],
            fail_silently=False,
        )

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm

from .models import CustomUser


class CustomUserForm(UserCreationForm):
    username = forms.CharField(
        label='Username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={
        'required': 'Sorry, you will need an email'})

    class Meta:
        model = CustomUser
        fields = ('email', 'username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update(
            {"placeholder": "Email"})
        self.fields['username'].widget.attrs.update(
            {"placeholder": "Username"})
        self.fields['password1'].widget.attrs.update(
            {"placeholder": "Password"})
        self.fields['password2'].widget.attrs.update(
            {"placeholder": "Confirm password"})

    def clean_username(self):
        username = self.cleaned_data['username']
        if CustomUser.objects.filter(username=username).exists():
            raise forms.ValidationError(
                "User with this username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'User with this email already exists')
        return email


class UserEditForm(forms.ModelForm):
    username = forms.CharField(
        label='Username', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Username', 'id': 'form-firstname'}))

    class Meta:
        model = CustomUser
        fields = ('username',)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        self.fields['username'].required = True

    def clean_username(self):
        username = self.cleaned_data['username']
        if CustomUser.objects.exclude(pk=self.request.user.pk).filter(username=username).exists():
            raise forms.ValidationError(
                "User with this username already exists")
        return username


class PasswordResetForm(PasswordResetForm):
    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = CustomUser.objects.filter(email=email)
        if not user:
            raise forms.ValidationError(
                'We could not find your account')
        return email


class PasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Confirm password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Confirm Password', 'id': 'form-new-pass2'}))

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_text
from django.template.loader import render_to_string

from .decorators import unauthenticated_user
from .forms import CustomUserForm, UserEditForm
from .token import account_activation_token
from accounts.models import CustomUser

# Create your views here.


@unauthenticated_user
def register(request):
    form = CustomUserForm()

    if request.method == "POST":
        form = CustomUserForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = "Activate your Account"
            message = render_to_string(
                "accounts/account_activation_email.html",
                {
                    "user": user,
                    "domain": current_site.domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": account_activation_token.make_token(user),
                },
            )
            user.email_user(subject=subject, message=message)
            messages.success(
                request, "User registered successfully, an activation email has been sent")
            return redirect('accounts:login-user')

    return render(request, 'accounts/register.html', {"form": form})


def account_activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "Account activated successfully")
        return redirect("products:all_products")
    else:
        messages.error(request, "Account activation invalid")
        return redirect("products:all_products")


@unauthenticated_user
def login_user(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('products:all_products')
        else:
            messages.error(request, "Email or password are incorrect")

    return render(request, 'accounts/login_user.html')


@login_required
def logout_user(request):
    logout(request)
    return redirect('accounts:login-user')


@login_required
def dashboard(request):
    form = UserEditForm(instance=request.user)
    return render(request, "accounts/dashboard.html", {"form": form})


@login_required
def edit_account(request):
    if request.method == "POST":
        form = UserEditForm(instance=request.user,
                            data=request.POST, request=request)

        if form.is_valid():
            form.save()
            messages.success(request, "Your account has been updated")
        return render(request, "accounts/dashboard.html", {"form": form})


@login_required
def delete_account(request):
    user = CustomUser.objects.get(username=request.user.username)
    user.is_active = False
    user.save()
    logout(request)
    messages.success(request, "User deleted successfully")
    return redirect("accounts:login-user")

templates/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Your account has been successfully created. Please click below link to activate your account

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Dashboard | Quipy</title>
	<link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet" />
	<link href="{% static 'css/price-range.css' %}" rel="stylesheet" />
	<link href="{% static 'css/animate.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section class="account-form"><!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <div class="signup-form"><!--sign up form-->
                    {% include 'messages.html' %}
                    <h2>Account details</h2>
                    {% for error in form.non_field_errors %}
                        <div class="text-danger">{{ error|escape }}</div>
                    {% endfor %} 
                    {% if form.errors %}
                    {% for field in form %}
                        {% if field.errors %}
                        {% for error in field.errors %}
                            <div class="text-danger" role="alert">
                            <p>{{ field.label }}: {{ error }}<p>
                            </div>
                        {% endfor %}
                        {% endif %}
                    {% endfor %}
                    {% endif %}

                    <form method="POST" action="{% url 'accounts:edit_account' %}">
                    {% csrf_token %}
                    <label class="form-label">Email (you can not change your email)</label>
                    <input type="text" value={{request.user.email}} readonly>
                    <label class="form-label">{{form.username.label}}</label>
                    {{form.username}}
                    <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                </div><!--/sign up form-->
            </div>
            <div class="col-sm-2"></div>
            <div class="col-sm-5">
                    <div class="signup-form"><!--sign up form-->
                        <div class="delete-account">
                            <h2>Delete account</h2>
                            <p>Are you sure you want to delete your account?</p>
                            <button class="btn btn-danger" data-toggle="modal" data-target="#delete-modal">Delete account</button>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <div id="delete-modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete Account</h4>
            </div>
            <div class="modal-body">
                <p>Your account will be set as inactive and you will not longer be able to access it.</p>
            </div>
            <form method="POST" class="modal-footer" action="{% url 'accounts:delete_account' %}">
                {% csrf_token %}
                <button type="button" class="btn btn-default" data-dismiss="modal">Keep Account</button>
                <button type="submit" class="btn btn-danger">Delete Account</button>
            </form>
            </div><!-- /.modal-content -->
         </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
</section><!--/form-->
{% include 'footer.html' %}
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/price-range.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
{% endblock scripts %}

templates/accounts/login_user.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section id="form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-4 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<h2>Login to your account</h2>
            			{% include 'messages.html' %}
						<form method="POST">
              				{% csrf_token %}
              				<label class="form-label">Email</label>
							<input type="text" placeholder="Enter Email" name="email" />
              				<label class="form-label">Password</label>
							<input type="password" placeholder="Enter Password" name="password" />
              				<p>You don't have an account? <a href="{% url 'accounts:register' %}">Register</a></p>
              				<p>Forgot your password? <a href="{% url 'accounts:password_reset' %}">Reset Password</a></p>
							<button type="submit" class="btn btn-default">Login</button>
						</form>
					</div><!--/login form-->
				</div>
			</div>
		</div>
	</section><!--/form-->
{% include 'footer.html' %}
{% endblock content %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block meta %}
<title>Password Reset Confirm | Quipy</title>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section id="form"><!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-1">
                <div class="login-form"><!--login form-->
                    <h2>Change your password</h2>
                    {% for error in form.non_field_errors %}
                    <div class="text-danger">{{ error|escape }}</div>
                    {% endfor %} 
                    {% if form.errors %}
                    {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                        <div class="text-danger" role="alert">
                            <p>{{ field.label }}: {{ error }}<p>
                        </div>
                        {% endfor %}
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        <label class="form-label">{{form.new_password1.label}}</label>
                        {{form.new_password1}}
                        <label class="form-label">{{form.new_password2.label}}</label>
                        {{form.new_password2}}
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                </div><!--/login form-->
            </div>
        </div>
    </div>
</section><!--/form-->
{% include 'footer.html' %}
{% endblock content %}

templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block meta %}
<title>Password Reset | Quipy</title>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section id="form"><!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-1">
                <div class="login-form"><!--login form-->
                    <h2>Request a new password</h2>
                    {% for error in form.non_field_errors %}
                    <div class="text-danger">{{ error|escape }}</div>
                    {% endfor %} 
                    {% if form.errors %}
                    {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                        <div class="text-danger" role="alert">
                            <p>{{ field.label }}: {{ error }}<p>
                        </div>
                        {% endfor %}
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                    <form method="POST" action="{% url 'accounts:password_reset' %}">
                        {% csrf_token %}
                        <label class="form-label">{{form.email.label}}</label>
                        {{form.email}}
                        <button type="submit" class="btn btn-default">Send email</button>
                    </form>
                </div><!--/login form-->
            </div>
        </div>
    </div>
</section><!--/form-->
{% include 'footer.html' %}
{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Register | Quipy</title>
	<link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet" />
	<link href="{% static 'css/price-range.css' %}" rel="stylesheet" />
	<link href="{% static 'css/animate.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section id="form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div class="signup-form"><!--sign up form-->
						<h2>New User Signup!</h2>
            {% for error in form.non_field_errors %}
              <div class="text-danger">{{ error|escape }}</div>
            {% endfor %} 
            {% if form.errors %}
            {% for field in form %}
              {% if field.errors %}
                {% for error in field.errors %}
                  <div class="text-danger" role="alert">
                    <p>{{ field.label }}: {{ error }}<p>
                  </div>
                {% endfor %}
              {% endif %}
            {% endfor %}
            {% endif %}

						<form method="POST">
              {% csrf_token %}
              <label class="form-label">{{form.username.label}}</label>
							{{form.username}}
              <label class="form-label">{{form.email.label}}</label>
							{{form.email}}
              <label class="form-label">{{form.password1.label}}</label>
							{{form.password1}}
              <label class="form-label">Confirm Password</label>
              {{form.password2}}
              <p>Already have an account? <a href="{% url 'accounts:login-user' %}">Login</a></p>
							<button type="submit" class="btn btn-default">Signup</button>
						</form>
					</div><!--/sign up form-->
				</div>
			</div>
		</div>
	</section><!--/form-->
{% include 'footer.html' %}
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/price-range.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
{% endblock scripts %}

templates/accounts/reset_status.html
{% extends 'base.html' %}

{% block meta %}
<title>Reset Status | Quipy</title>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section id="form"><!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-sm-offset-1">
                <div class="login-form"><!--login form-->
                    {% if 'email' in request.get_full_path %}
                        <h3 class="mb-4">Password Reset Success</h3>
                        <p>Check your email for instructions</p>
                    {% endif%}
                    {% if 'complete' in request.get_full_path %}
                        <h3 class="mb-4">Password Reset Success</h3>
                        <a href="{% url "accounts:login-user" %}">Login</a>
                    {% endif%}
                </div><!--/login form-->
            </div>
        </div>
    </div>
</section><!--/form-->
{% include 'footer.html' %}
{% endblock content %}