accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views
from .forms import PasswordResetForm, PasswordResetConfirmForm


app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/",
         views.account_activate, name="activate"),
    path('login-user/', views.login_user, name="login-user"),
    path('logout/', views.logout_user, name="logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('edit-account/', views.edit_account, name="edit_account"),
    path("delete-account/", views.delete_account, name="delete_account"),
    path("password_reset/", auth_views.PasswordResetView.as_view(
        template_name="accounts/password_reset_form.html",
        success_url="password_reset_email_confirm/",
        email_template_name="accounts/password_reset_email.html",
        form_class=PasswordResetForm
    ), name="password_reset"),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/accounts/password_reset_complete/",
            form_class=PasswordResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="accounts/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_complete/",
        TemplateView.as_view(template_name="accounts/reset_status.html"),
        name="password_reset_complete",
    ),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name="cart"),
    path("cart-add/", views.cart_add, name="cart_add"),
    path("cart-delete/", views.cart_delete, name="cart_delete"),
    path("cart-update/", views.cart_update, name="cart_update")
]

payment/urls.py
from django.urls import path
from . import views

app_name = "payment"

urlpatterns = [
    path("checkout/", views.checkout, name="checkout"),
    path("order-placed/", views.order_placed, name="order_placed"),
    path("webhook/", views.stripe_webhook)
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.all_products, name="all_products"),
    path('shop/', views.shop, name="shop"),
    path('product/<slug:slug>/', views.product_detail, name="product_detail"),
    path('search/<slug:slug>/', views.get_by_category, name="category")
]

quipy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls")),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('payment/', include("payment.urls")),
    path('orders/', include("orders.urls"))
]

handler404 = "quipy.views.page_not_found"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    {% block meta %}{% endblock %}
  </head>
  <body>
    {% block content %} {% endblock %}

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %} {% endblock %}
    <script src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
  </body>
</html>

templates/footer.html
{% load static %}
<footer id="footer">
  <!--Footer-->
  

  <div class="footer-widget">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Service</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Online Help</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Order Status</a></li>
              <li><a href="#">Change Location</a></li>
              <li><a href="#">FAQ’s</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Quock Shop</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">T-Shirt</a></li>
              <li><a href="#">Mens</a></li>
              <li><a href="#">Womens</a></li>
              <li><a href="#">Gift Cards</a></li>
              <li><a href="#">Shoes</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Policies</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Terms of Use</a></li>
              <li><a href="#">Privecy Policy</a></li>
              <li><a href="#">Refund Policy</a></li>
              <li><a href="#">Billing System</a></li>
              <li><a href="#">Ticket System</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>About Shopper</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Company Information</a></li>
              <li><a href="#">Careers</a></li>
              <li><a href="#">Store Location</a></li>
              <li><a href="#">Affillate Program</a></li>
              <li><a href="#">Copyright</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
          <div class="single-widget">
            <h2>About Shopper</h2>
            <form action="#" class="searchform">
              <input type="text" placeholder="Your email address" />
              <button type="submit" class="btn btn-default">
                <i class="fa fa-arrow-circle-o-right"></i>
              </button>
              <p>
                Get the most recent updates from <br />our site and be updated
                your self...
              </p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <p class="pull-left">
          Copyright © 2013 E-SHOPPER Inc. All rights reserved.
        </p>
        <p class="pull-right">
          Designed by
          <span
            ><a target="_blank" href="http://www.themeum.com">Themeum</a></span
          >
        </p>
      </div>
    </div>
  </div>
</footer>
<!--/Footer-->

templates/messages.html
{% if messages %}
{% for message in messages %}
{% if message.tags == "success" %}
<div class="alert alert-success show mb-2 mt-2" role="alert">{{message}}</div>
{% elif message.tags == "info" %}
<div class="alert alert-primary show mb-2 mt-2" role="alert">{{message}}</div>
{% else %}
<div class="alert alert-danger show mb-2 mt-2" role="alert">{{message}}</div>
{% endif %}
{% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

<header id="header">
  <!--header-->

  {% with request.resolver_match.url_name as url_name %}
  <div class="header-middle">
    <!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="logo pull-left">
            <a href="index.html"><img src="images/home/logo.png" alt="" /></a>
          </div>

        </div>
        <div class="col-sm-8">
          <div class="shop-menu pull-right">
            <ul class="nav navbar-nav">
              <li>
                <a href="{% url 'accounts:dashboard' %}"><i class="fa fa-user"></i> Account</a>
              </li>
              <li>
                <a href="#"><i class="fa fa-star"></i> Wishlist</a>
              </li>
              <li>
                <a href="{% url 'payment:checkout' %}"><i class="fa fa-crosshairs"></i> Checkout</a>
              </li>
              <li>
              {% with total_qty=cart|length %}
                <a href="{% url 'cart:cart' %}">
                  {% if total_qty > 0 %}
                    <span id="cart-count" class="badge badge-primary">{{total_qty}}</span>
                  {% else %}
                    <span id="cart-count" class="badge badge-primary">0</span>
                  {% endif %}
                <i class="fa fa-shopping-cart"></i> Cart</a>
              {% endwith %}
              </li>
              {% if user.is_authenticated %}
                <li>
                  <a href="{% url 'accounts:logout' %}"><i class="fa fa-lock"></i> Logout</a>
                </li>
              {% else %}
                <li>
                  <a href="{% url 'accounts:login-user' %}"><i class="fa fa-lock"></i> Login</a>
                </li>
                <li>
                  <a href="{% url 'accounts:register' %}"><i class="fa fa-lock"></i> Register</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header-middle-->

  <div class="header-bottom">
    <!--header-bottom-->
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a href="{% url 'products:all_products' %}"
                  class="{% if url_name == 'all_products' %}active{% endif %}">Home</a></li>
              <li><a href="{% url 'products:shop' %}" class="{% if url_name == 'shop' %}active{% endif %}">Shop</a></li>
              <li><a href="contact-us.html">Contact</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <input type="text" placeholder="Search" />
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/header-bottom-->
  {% endwith %}
</header>
<!--/header-->